services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - .:/code

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cozyquarter
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-container
    depends_on:
      - db
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
